apiVersion: v2
name: myhome
description: MyHome Spring Boot Application Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - myhome
  - spring-boot
  - mysql
maintainers:
  - name: MyHome Team